const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@SnapKart Devs";
  const  emailHint= "eg. orusmail@example.com";
  const passHint= "********";
  const dashBoard= "Dashboard";
  const products= "Products";
  const orders = "Orders";
  const generalSettings= "General Settings";
  const rating= "Rating";
  const totalSales ="Total Sales";
  const popular= "Popular Products";
  const unPaid= "Unpaid";
  const featured= "Featured";
  const edit= "Edit";
  const delete= "Delete";
  const settings="Settings";
  const shopSetting="Shop Settings";
  const messages= "Messages";
  const editProfile="Edit Profile";
  const changeImage= "Change Image";
  const name= "Name";
  const nameHint= "eg. Snapkart Dev";
  const shopDescHint= "eg. Dairy Shop";
  const shopWebsiteHint= "eg. foulcart.com";
  const mobileHint= "eg. +910000000000";
  const addressHint = "eg. near Borabazzar";
  const desc= "Shop Description";
  const address= "Shop Address";
  const mobile= "Mobile Number";
  const webSite= "Website";
  const shopName= "Shop Name";
  const shopNameHint= "eg. Ma Parbati Dairy ent.";
  const confirmPassword="Confirm Password";

  const orderDetails="Order Details";

  //*Order Details Screen
  const orderCode= "Order Code";
  const shippingMethod= "Shipping Method";
  const orderDate="Order Date";
  const paymentStatus= "Payment Status";
  const paymentMethod="Payment Method";
  const deliveryStatus= "Delivery Status";
  const shippingAddress= "Shipping Address";
  const totalAmmount= "Total Ammount";
  